export const SETTINGS_CURRENT_VTRQ_SET = 'SETTINGS_CURRENT_VTRQ_SET';
export const WORKSPACE_EDIT_ENTRY_CREATE = 'WORKSPACE_EDIT_ENTRY_CREATE';
export const WORKSPACE_EDIT_ENTRY_DELETE = 'WORKSPACE_EDIT_ENTRY_DELETE';
export const WORKSPACE_EDIT_ENTRY_MOVE = 'WORKSPACE_EDIT_ENTRY_MOVE';
export const WORKSPACE_EDIT_ENTRY_LOCAL = 'WORKSPACE_EDIT_ENTRY_LOCAL';
export const WORKSPACE_EDIT_ENTRY_VP_PATH = 'WORKSPACE_EDIT_ENTRY_VP_PATH';
export const WORKSPACE_EDIT_ENTRY_VTRQ = 'WORKSPACE_EDIT_ENTRY_VTRQ';
export const WORKSPACE_EDIT_ENTRY_VTRQ_PATH = 'WORKSPACE_EDIT_ENTRY_VTRQ_PATH';
export const WORKSPACE_EDIT_CANCEL = 'WORKSPACE_EDIT_CANCEL';
export const WORKSPACE_EDIT_INIT = 'WORKSPACE_EDIT_INIT';
export const WORKSPACE_EDIT_NAME = 'WORKSPACE_EDIT_NAME';

export const WORKSPACES_DELETE_REQUEST = 'WORKSPACES_DELETE_REQUEST';
export const WORKSPACES_DELETE_SUCCESS = 'WORKSPACES_DELETE_SUCCESS';
export const WORKSPACES_DELETE_FAILURE = 'WORKSPACES_DELETE_FAILURE';

export const WORKSPACES_GET_ALL_REQUEST = 'WORKSPACES_GET_ALL_REQUEST';
export const WORKSPACES_GET_ALL_SUCCESS = 'WORKSPACES_GET_ALL_SUCCESS';
export const WORKSPACES_GET_ALL_FAILURE = 'WORKSPACES_GET_ALL_FAILURE';

export const WORKSPACES_REPLACE_REQUEST = 'WORKSPACES_REPLACE_REQUEST';
export const WORKSPACES_REPLACE_SUCCESS = 'WORKSPACES_REPLACE_SUCCESS';
export const WORKSPACES_REPLACE_FAILURE = 'WORKSPACES_REPLACE_FAILURE';
