#!/usr/bin/env bash

NODE_VERSION=v6.6.0

#
#  Locate ourselves.
#
VELSTOR_VCNC_DIR="$(dirname "$(readlink -f "$0")")/.."
#
#  Check our node installation
#
NVM_DIR=$VELSTOR_VCNC_DIR/share/vcnc/nvm
#  .. Does nvm exist?
if [ ! -d "$NVM_DIR" ]; then
  echo "VCNC: $NVM_DIR missing. Exiting.";  exit 1
fi
#
#  Sanity spot-check our installation
#
SERVER_DIR="$VELSTOR_VCNC_DIR/share/vcnc/vcnc-rest"
if [ ! -d $SERVER_DIR/node_modules ]; then 
  echo "VCNC: $SERVER_DIR/node_modules doesn't exist. Exiting."; exit 6
fi
NODE_APP="$SERVER_DIR/app.js"
if [ ! -s $NODE_APP ]; then 
  echo "VCNC: $NODE_APP empty or doesn't exist. Exiting."; exit 7
fi
#
#  Did we correctly locate node.js?
#
NODE_EXE="$NVM_DIR/versions/node/$NODE_VERSION/bin/node"
if [ ! -x $NODE_EXE ]; then
  echo "VCNC: $NODE_EXE not found or not executable. Exiting."; exit 8
fi
#
#  Set our LD_LIBRARY_PATH
#
export LD_LIBRARY_PATH="$VELSTOR_VCNC_DIR/lib64"
if [ ! -d "$LD_LIBRARY_PATH" ]; then 
  echo "VCNC: $LD_LIBRARY_PATH doesn\'t exist. Exiting."; exit 9
fi
#
#  Start the server
#
$NODE_EXE $NODE_APP








